# Site settings
title: Tech Ka Banda
description: "Life, Code, Poetry"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://www.techkabanda.com" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: codeon 
user_title: Kapil Garg
email: ask.codeon@gmail.com
twitter_username: iKapilGarg
github_username:  codeon
linkedin_public_url: kapilgarg12 # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
profile_picture: https://media.licdn.com/dms/image/C4E03AQEPh-XPwn6zxQ/profile-displayphoto-shrink_200_200/0?e=1561593600&v=beta&t=hxHymNMpd-zHYI47TEzLvEXuckA6BPIdwSPYtrlbkoY

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/codeon
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/iKapilGarg
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
